name: Weekly Updates

on:
  schedule:
    - cron: "30 11 * * 1"

jobs:
  update_deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: |
          bun upgrade
          bun install

      - name: Commit and Push
        run: |
          git config --global user.email "${{ secrets.MY_EMAIL }}"
          git config --global user.name "${{ secrets.MY_NAME }}"
          git add .
          git commit -m "build(deps): Weekly Update by GitHub Actions"
          git push origin main
